<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MoviesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('movies')->delete();
        
        \DB::table('movies')->insert(array (
            0 => 
            array (
                'id' => 6,
                'name' => 'Biệt Đội Siêu Anh Hùng 4: Hồi Kết',
                'eng_name' => 'Avengers 4: Endgame',
                'description' => '<p>Sau sự kiện hủy diệt tàn khốc, vũ trụ chìm trong cảnh hoang tàn. Với sự trợ giúp của những đồng minh còn sống sót, biệt đội siêu anh hùng Avengers tập hợp một lần nữa để đảo ngược hành động của Thanos và khôi phục lại trật tự của vũ trụ.</p>',
                'language' => 'Anh',
                'studio' => 'marvel',
                'releasedate' => '2019-04-26',
                'runtime' => 180,
                'avgrating' => 0.0,
                'view' => 42,
                'category_id' => 1,
                'country_id' => 2,
                'profileimage_id' => 18,
                'coverimage_id' => 19,
                'trailer_id' => 8,
                'created_at' => '2021-04-20 16:08:20',
                'updated_at' => '2022-04-07 13:24:34',
            ),
            1 => 
            array (
                'id' => 8,
            'name' => 'Cậu bé mất tích( phần 3)',
            'eng_name' => 'Stranger Things (Season 3) (2019)',
                'description' => '<p>Lấy bối cảnh những năm 1980 tại thị trấn Hawkins yên bình, cậu bé Will đột nhiên mất tích một cách bí ẩn. Mẹ cậu - Joyce ngày đêm tìm kiếm con trai mình trong tuyệt vọng. Bức màn dần được vén lên khi cô phát hiện ra rằng sự biến mất của Will rất có thể dính dáng đến chính phủ và những thế lực siêu nhiên. Cùng lúc đó, một cô bé sở hữu những khả năng kỳ dị đột nhiên xuất hiện...</p>',
                'language' => 'Anh',
                'studio' => 'netflix',
                'releasedate' => '2019-07-05',
                'runtime' => 60,
                'avgrating' => 2.0,
                'view' => 20,
                'category_id' => 2,
                'country_id' => 2,
                'profileimage_id' => 22,
                'coverimage_id' => 23,
                'trailer_id' => 10,
                'created_at' => '2021-04-20 17:26:57',
                'updated_at' => '2022-03-31 14:58:34',
            ),
            2 => 
            array (
                'id' => 9,
                'name' => 'Chim Ưng và Chiến Binh Mùa Đông',
                'eng_name' => 'The Falcon and the Winter Soldier',
                'description' => '<p>Giống với WandaVision, The Falcon and the Winter Soldier được lấy bối cảnh hậu sự kiện Avengers: Endgame. Nhờ vào cú búng tay của Hulk, sự trở lại của một nửa sinh linh Trái Đất đã mất trước đó tuy là một điều tốt đẹp, nhưng mặc khác, điều này cũng gây nên nhiều cuộc khủng hoảng trầm trọng trên toàn thế giới, và nước Mỹ cũng không nằm ngoài số đó. Lợi dụng tình hình loạn lạc hiện tại, một nhóm lính đánh thuê bí ẩn bắt đầu gây nên nhiều vụ khủng bố trầm trọng khiến chính quyền phải ra tay.</p>',
                'language' => 'Mỹ',
                'studio' => 'marvel',
                'releasedate' => '2021-04-03',
                'runtime' => 45,
                'avgrating' => 0.0,
                'view' => 3,
                'category_id' => 2,
                'country_id' => 2,
                'profileimage_id' => 24,
                'coverimage_id' => 25,
                'trailer_id' => 11,
                'created_at' => '2021-04-20 17:32:18',
                'updated_at' => '2022-04-07 14:32:43',
            ),
            3 => 
            array (
                'id' => 10,
            'name' => 'điềm báo( phần 1)',
            'eng_name' => 'good omens( season 1)',
            'description' => '<p>Thiện Báo:Phần 1 (Good Omens: Season 1) :&nbsp;Vào đầu và mười một năm trước, hai sinh vật bất tử quyết định rằng có lẽ không đến lúc bắt đầu một Ngày tận thế. Đã theo dõi cậu bé sai lầm trong nhiều năm, Aziraphale và Crowley giờ phải cố gắng xác định vị trí của Antichrist thực sự. Có lẽ câu chuyện về Agnes Nutter và những lời tiên tri nổi tiếng của cô sẽ giữ câu trả lời?</p>',
                'language' => 'Mỹ',
                'studio' => 'marvel',
                'releasedate' => '2019-02-15',
                'runtime' => 60,
                'avgrating' => 0.0,
                'view' => 10,
                'category_id' => 2,
                'country_id' => 2,
                'profileimage_id' => 31,
                'coverimage_id' => 32,
                'trailer_id' => 12,
                'created_at' => '2021-04-21 14:33:48',
                'updated_at' => '2021-06-02 13:01:59',
            ),
            4 => 
            array (
                'id' => 11,
            'name' => 'siêu anh hùng phá hoại( phần 1)',
            'eng_name' => 'the boys( season 1)',
                'description' => '<p>Siêu anh hùng là những người sử dụng sức mạnh của mình để giải cứu Trái Đất và mang lại bình yên cho nhân loại” – Đó là triết lý được các phim bom tấn của Marvel hay DC mang đến cho khán giả. Siêu anh hùng luôn xuất hiện “ngầu lòi”, đạo đức “chói lóa”, mang đến hòa bình, hạnh phúc ấm no muôn nơi. Nhưng sẽ thế nào nếu chính siêu anh hùng là những người... khiến thế giới tồi tệ hơn. Một đội chống các siêu anh hùng đã được lập ra để vạch trần những siêu anh hùng biến chất.</p>',
                'language' => 'Mỹ',
                'studio' => 'Amazon Prime',
                'releasedate' => '2019-07-26',
                'runtime' => 70,
                'avgrating' => 0.0,
                'view' => 0,
                'category_id' => 2,
                'country_id' => 2,
                'profileimage_id' => 33,
                'coverimage_id' => 34,
                'trailer_id' => 13,
                'created_at' => '2021-04-21 14:46:37',
                'updated_at' => '2021-04-21 14:46:37',
            ),
            5 => 
            array (
                'id' => 12,
            'name' => 'siêu anh hùng phá hoại( phần 2)',
            'eng_name' => 'the boys( season 2)',
                'description' => '<p>Siêu anh hùng là những người sử dụng sức mạnh của mình để giải cứu Trái Đất và mang lại bình yên cho nhân loại” – Đó là triết lý được các phim bom tấn của Marvel hay DC mang đến cho khán giả. Siêu anh hùng luôn xuất hiện “ngầu lòi”, đạo đức “chói lóa”, mang đến hòa bình, hạnh phúc ấm no muôn nơi. Nhưng sẽ thế nào nếu chính siêu anh hùng là những người... khiến thế giới tồi tệ hơn. Một đội chống các siêu anh hùng đã được lập ra để vạch trần những siêu anh hùng biến chất.</p>',
                'language' => 'Mỹ',
                'studio' => 'Amazon Prime',
                'releasedate' => '2020-09-04',
                'runtime' => 60,
                'avgrating' => 0.0,
                'view' => 0,
                'category_id' => 2,
                'country_id' => 2,
                'profileimage_id' => 35,
                'coverimage_id' => 36,
                'trailer_id' => 14,
                'created_at' => '2021-04-21 14:51:11',
                'updated_at' => '2021-04-21 14:51:11',
            ),
            6 => 
            array (
                'id' => 13,
                'name' => 'biệt đội siêu anh hùng 3: cuộc chiến vô cực',
            'eng_name' => 'Avengers 3: Infinity War (2018)',
                'description' => '<p>Sau chuyến hành trình độc nhất vô nhị không ngừng mở rộng và phát triển vụ trũ điện ảnh Marvel, bộ phim Avengers: Cuộc Chiến Vô Cực sẽ mang đến màn ảnh trận chiến cuối cùng khốc liệt nhất mọi thời đại. Biệt đội Avengers và các đồng minh siêu anh hùng của họ phải chấp nhận hy sinh tất cả để có thể chống lại kẻ thù hùng mạnh Thanos trước tham vọng hủy diệt toàn bộ vũ trụ của hắn.</p>',
                'language' => 'Anh',
                'studio' => 'marvel',
                'releasedate' => '2018-04-25',
                'runtime' => 149,
                'avgrating' => 0.0,
                'view' => 7,
                'category_id' => 1,
                'country_id' => 2,
                'profileimage_id' => 37,
                'coverimage_id' => 38,
                'trailer_id' => 15,
                'created_at' => '2021-04-21 14:58:44',
                'updated_at' => '2021-11-04 16:06:20',
            ),
            7 => 
            array (
                'id' => 14,
                'name' => 'biệt đội siêu anh hùng 2: đế chế Ultron',
                'eng_name' => 'avengers 2: age of ultron',
                'description' => '<p>Trong phần này, biệt đội siêu anh hùng của chúng ta sẽ phải chiến đấu với binh đoàn robot được biết đến với cái tên là Ultron.</p>',
                'language' => 'Anh',
                'studio' => 'marvel',
                'releasedate' => '2015-04-24',
                'runtime' => 150,
                'avgrating' => 0.0,
                'view' => 4,
                'category_id' => 1,
                'country_id' => 2,
                'profileimage_id' => 39,
                'coverimage_id' => 40,
                'trailer_id' => 16,
                'created_at' => '2021-04-21 15:09:51',
                'updated_at' => '2021-05-07 13:26:19',
            ),
            8 => 
            array (
                'id' => 15,
                'name' => 'biệt đội siêu anh hùng',
            'eng_name' => 'the avengers( 2012)',
                'description' => '<p>Marvel’s The Avengers là bộ phim giả tưởng kể về một nhóm siêu anh hùng với những khả năng đặc biệt, họ bao gồm: Người Sắt, Thor, Captain America, và Người Khổng Lồ được gọi chung với cái tên SHIELD. Mục đích của SHIELD là nhằm bảo vệ Trái đất khỏi âm mưu hủy hoại của những thế lực xấu từ ngoài địa cầu mà kẻ cầm đầu là Loki. Marvel’s The Avengers Là một trong những phim được mong đợi nhất hè 2012, phim quy tụ dàn diễn viên đẹp với những cảnh quay sống động đã mang về cho nhà sản xuất hơn 1 tỷ USD. Nếu bạn đã từng là Fan của những siêu phẩm như: Spider-Man, Batman thì Marvel’s The Avengers quả là một bộ phim khó có thể bỏ qua.</p>',
                'language' => 'Anh',
                'studio' => 'marvel',
                'releasedate' => '2012-04-25',
                'runtime' => 143,
                'avgrating' => 0.0,
                'view' => 8,
                'category_id' => 1,
                'country_id' => 2,
                'profileimage_id' => 41,
                'coverimage_id' => 42,
                'trailer_id' => 17,
                'created_at' => '2021-04-21 15:22:10',
                'updated_at' => '2021-05-06 14:53:00',
            ),
            9 => 
            array (
                'id' => 16,
                'name' => 'chúa tể của những chiếc nhẫn 1: hiệp hội nhẫn thần',
            'eng_name' => 'the lord of the rings: the fellowship of the rings( 2001)',
                'description' => '<p>Chiếc nhẫn chúa mang sức mạnh bá chủ vô tình được số phận đưa vào tay chàng hobbit trẻ tuổi Frodo. Khi thày phù thủy Gandalf phát hiện ra chiếc nhẫn này đã từng thuộc về bạo chúa Sauron, Frodo phải nhận nhiệm vụ mang nhẫn tới khe núi Hủy diệt để tiêu hủy nó.<br><br>Không đơn độc trong hành trình gian khó, Frodo còn tiếp nhận những người đồng hành thuộc các tộc khác nhau: Legolas tộc Elf; Gimli tộc Dwarf; Aragon, Boromir và ba người bạn Hobbit trung thành...<br><br>Phim là phần đầu trong bộ ba kinh điển "Chúa tể những chiếc nhẫn", chuyển thể từ thiên truyện của nhà văn Tolkien.</p>',
                'language' => 'Anh',
                'studio' => 'New Line Cinema',
                'releasedate' => '2001-12-10',
                'runtime' => 178,
                'avgrating' => 0.0,
                'view' => 2,
                'category_id' => 1,
                'country_id' => 10,
                'profileimage_id' => 43,
                'coverimage_id' => 44,
                'trailer_id' => 18,
                'created_at' => '2021-04-21 15:34:47',
                'updated_at' => '2021-05-07 11:51:45',
            ),
            10 => 
            array (
                'id' => 17,
                'name' => 'chúa tể của những chiếc nhẫn 2: hai tòa tháp',
            'eng_name' => 'the lord of the rings 2: the two towers( 2002)',
                'description' => '<p>Cuộc hành trình đi hủy diệt chiếc nhẫn tiếp tục với bao nguy hiểm chờ đợi Frodo ở phía trước. Lần này, anh và Sam có một bạn đồng hành mới là Gollum. Trong khi đó, Gandalf may mắn thoát chết, hơn nữa sức mạnh của ông còn vượt xa hơn rất nhiều. Ông cùng Aragon, Legolas và Gimli cùng những thần rừng tìm cách phá hủy âm mưu của Saruman. Tiếp nối thành công của phần 1 The Lord Of The Ring 2 kế thừa và đan xen giữa hai hệ thống nhân vật cũ và mới làm cho nội dung phim càng thêm lôi cuốn người xem. The Lord Of The Ring 2 cũng mang về 2 Giải Oscar cho hạng mục âm thanh và Kĩ xảo</p>',
                'language' => 'Anh',
                'studio' => 'New Line Cinema',
                'releasedate' => '2002-12-05',
                'runtime' => 179,
                'avgrating' => 0.0,
                'view' => 2,
                'category_id' => 1,
                'country_id' => 10,
                'profileimage_id' => 45,
                'coverimage_id' => 46,
                'trailer_id' => 19,
                'created_at' => '2021-04-21 15:38:00',
                'updated_at' => '2021-05-08 14:23:20',
            ),
            11 => 
            array (
                'id' => 18,
                'name' => 'chúa tể của những chiếc nhẫn 3: sự trở lại của nhà vua',
            'eng_name' => 'the lord of the rings 3: the return of the king( 2003)',
                'description' => '<p>Sauron huy động toàn lực cho trận chiến khốc liệt cuối cùng, tấn công vào Gondor – vùng đất huyết mạch của loài người. Gondor dưới sự lãnh đạo của vị vua nhu nhược trở nên quá mong manh và nguy ngập. Đó chính là lúc những người anh hùng phát huy hết khả năng của mình. Cùng với sự hỗ trợ của các chiến binh Rohan, lực lượng những hồn ma bị nguyền rủa trong khe núi, Aragorn đã thống lĩnh những người Gondor chống lại Sauron, anh đã thực hiện sứ mệnh mà số phận giao phó cho mình, Aragorn sinh ra để trở thành Vua của Gondor, anh đã chứng minh điều đó. Cùng lúc đó, Frodo và Sam tiếp tục dấn sâu vào vùng đất ma quỷ đầy hiểm nguy để thực thi sứ mạng của mình, sứ mạng tiêu hủy Chiếc Nhẫn Quyền Lực. Có thể nói Sự Trở Lại Của Nhà Vua Phim là phần có nội dung hấp dẫn cùng những màn chiến đấu cực hay, cực kỳ hoành tráng. "The Lord Of The Ring 3" không chỉ làm mê mẩn khán giả yêu phim mà còn chinh phục trái tim các nhà phê bình điện ảnh với 11 giải Oscar ‘2004 trong đó có Oscar Phim hay nhất và Oscar Đạo diễn xuất sắc nhất.</p>',
                'language' => 'Anh',
                'studio' => 'New Line Cinema',
                'releasedate' => '2003-12-01',
                'runtime' => 201,
                'avgrating' => 0.0,
                'view' => 3,
                'category_id' => 1,
                'country_id' => 10,
                'profileimage_id' => 47,
                'coverimage_id' => 48,
                'trailer_id' => 20,
                'created_at' => '2021-04-21 15:56:13',
                'updated_at' => '2021-05-07 13:15:38',
            ),
            12 => 
            array (
                'id' => 19,
                'name' => 'người hobbit: hành trình vô định',
            'eng_name' => 'the hobbit: an unexpected journey( 2012)',
                'description' => '<p>Trong thập niên 2000, câu chuyện về Người lùn, yêu tinh, các vị tiên, quái vật khổng lồ từng đem tới những trải nghiệm không thể nào quên với hàng triệu người yêu điện ảnh. Chính vì vậy, khi đạo diễn Peter Jackson quyết định thực hiện The Hobbit. The Hobbit đưa người xem trở về với thế giới Trung Địa huyền ảo và tham gia vào cuộc hành trình vô định của Bilbo Baggins – chú của nhân vật Frodo. Lấy mốc thời gian trước những sự kiện xảy ra trong ba phần Chúa Nhẫn, The Hobbit xoay quanh nhân vật Bilbo Baggins, người bị cuốn vào một chuyến phiêu lưu phi thường để đoạt lại xứ sở Người Lùn đang bị chiếm giữ bởi con rồng khổng lồ Smaug. Chuyến đi của Bilbo có sự hộ tống của Pháp sư Gandalf Áo Xám và 13 thành viên tộc Người Lùn mà dẫn đầu là hoàng tử Thorin Oakensheild. Cuộc hành trình đưa họ tới những vùng đất kỳ lạ của Trung Địa – nơi có những vị tiên lộng lẫy, những con yêu tinh khổng lồ, những phù thủy bí hiểm và cả những linh hồn giấu mặt đang theo dõi nhất cử nhất động của họ.</p>',
                'language' => 'Mỹ',
                'studio' => 'New Line Cinema',
                'releasedate' => '2012-12-28',
                'runtime' => 169,
                'avgrating' => 0.0,
                'view' => 4,
                'category_id' => 1,
                'country_id' => 2,
                'profileimage_id' => 49,
                'coverimage_id' => 50,
                'trailer_id' => 21,
                'created_at' => '2021-04-21 16:06:25',
                'updated_at' => '2021-05-08 14:23:14',
            ),
            13 => 
            array (
                'id' => 20,
                'name' => 'người hobbit 2: đại chiến với rồng lửa',
            'eng_name' => 'the hobbit 2: the desolation of dmaug( 2013)',
                'description' => '<p>Phim "Người Hobbit: Đại Chiến Với Rồng Lửa" tiếp tục kể về cuộc phiêu lưu của nhân vật chính Bilbo Baggins và cuộc hành trình với phù thuỷ Gandalf cùng mười ba người lùn dẫn đầu bởi Thorin Oakenshield, họ mang trên mình một nhiệm vụ sử thi để đòi lại Lonely Mountain và Vương quốc người lùn đã mất của Erebor.<br><br>Sống sót trong cuộc hành trình bất ngờ, cả đoàn đã đi về phía Đông, dọc đường họ đã gặp phải tộc người hoá gấu Beorn và một đàn nhện khổng lồ trong khu rừng nguy hiểm ở Mirkwood. Sau khi thoát khỏi móng vuốt của các Wood-Elf, các người lùn tìm đến thị trấn Lake và cuối cùng đến được Lonely Mountain - nơi họ phải đối mặt với nguy hiểm lớn nhất đó là một sinh vật đáng sợ hơn bất kỳ ai, thứ mà sẽ kiểm chứng không chỉ lòng dũng cảm mà thử thách cả giới hạn tình bạn của họ – Rồng Smaug.<br>&nbsp;</p>',
                'language' => 'Mỹ',
                'studio' => 'New Line Cinema',
                'releasedate' => '2013-12-02',
                'runtime' => 161,
                'avgrating' => 0.0,
                'view' => 3,
                'category_id' => 1,
                'country_id' => 2,
                'profileimage_id' => 51,
                'coverimage_id' => 52,
                'trailer_id' => 22,
                'created_at' => '2021-04-21 16:13:03',
                'updated_at' => '2021-05-08 01:43:21',
            ),
            14 => 
            array (
                'id' => 21,
                'name' => 'người hobbit 3: đại chiến 5 cánh quân',
            'eng_name' => 'the hobbit 3: the battle of the five armies( 2014)',
                'description' => '<p>Sau khi thành công tiến vào lãnh địa của con rồng Smaug, anh chàng Hobbit gan dạ Bilbo cùng những người đồng đội Dwarf của mình sẽ phải đối mặt với những nguy hiểm gì? Những đội quân Orc đang rình rập, liệu Thor Oakenshield có thành công giành lại vương quốc của mình hay không, và số phận của vùng Trung Địa sẽ xoay chuyển như thế nào khi thế lực bóng tối từ Modor dần dần hiện thân.</p>',
                'language' => 'Mỹ',
                'studio' => 'New Line Cinema',
                'releasedate' => '2014-12-01',
                'runtime' => 144,
                'avgrating' => 0.0,
                'view' => 2,
                'category_id' => 1,
                'country_id' => 2,
                'profileimage_id' => 53,
                'coverimage_id' => 54,
                'trailer_id' => 23,
                'created_at' => '2021-04-21 17:05:29',
                'updated_at' => '2021-05-07 13:25:49',
            ),
            15 => 
            array (
                'id' => 22,
                'name' => 'thợ săn quái vật',
                'eng_name' => 'the witcher',
            'description' => '<p>The Witcher được chuyển thể từ bộ tiểu thuyết nổi tiếng của nhà văn Ba Lan Andrzej Sapkowski, cũng như loạt game ăn khách cùng tên. Bối cảnh của The Witcher đặt tại một vùng đất hư cấu có tên Đại Lục (The Continent), tràn ngập những loài quái vật nguy hiểm. Một nhóm những chiến binh sở hữu siêu năng lực được tạo ra, được gọi là Witcher để săn lùng và tiêu diệt chúng.</p>',
                'language' => 'Mỹ',
                'studio' => 'netflix',
                'releasedate' => '2019-12-20',
                'runtime' => 60,
                'avgrating' => 0.0,
                'view' => 11,
                'category_id' => 2,
                'country_id' => 2,
                'profileimage_id' => 55,
                'coverimage_id' => 56,
                'trailer_id' => 24,
                'created_at' => '2021-04-26 02:57:57',
                'updated_at' => '2021-05-22 16:15:44',
            ),
            16 => 
            array (
                'id' => 23,
            'name' => 'học viện umbrella( phần 1)',
                'eng_name' => 'the umbrella academy',
                'description' => '<p>Đoàn tụ vì cái chết của cha, những anh chị em xa cách sở hữu năng lực siêu phàm bàng hoàng phát hiện ra bí mật gia đình -- và một nguy cơ đang dần hiện hữu với nhân loại.</p>',
                'language' => 'Mỹ',
                'studio' => 'netflix',
                'releasedate' => '2019-02-15',
                'runtime' => 50,
                'avgrating' => 0.0,
                'view' => 15,
                'category_id' => 2,
                'country_id' => 2,
                'profileimage_id' => 58,
                'coverimage_id' => 59,
                'trailer_id' => 25,
                'created_at' => '2021-04-26 15:42:45',
                'updated_at' => '2021-06-01 17:05:14',
            ),
            17 => 
            array (
                'id' => 24,
            'name' => 'Cậu bé mất tích( phần 1)',
            'eng_name' => 'Stranger Things (Season 1) (2016)',
                'description' => '<p>Phim Cậu Bé Mất Tích - Stranger Things 2016: Lấy bối cảnh những năm 1980 tại thị trấn Hawkins yên bình, cậu bé Will đột nhiên mất tích một cách bí ẩn. Mẹ cậu - Joyce ngày đêm tìm kiếm con trai mình trong tuyệt vọng. Bức màn dần được vén lên khi cô phát hiện ra rằng sự biến mất của Will rất có thể dính dáng đến chính phủ và những thế lực siêu nhiên. Cùng lúc đó, một cô bé sở hữu những khả năng kỳ dị đột nhiên xuất hiện...</p>',
                'language' => 'Mỹ',
                'studio' => 'netflix',
                'releasedate' => '2016-07-15',
                'runtime' => 50,
                'avgrating' => 0.0,
                'view' => 51,
                'category_id' => 2,
                'country_id' => 2,
                'profileimage_id' => 60,
                'coverimage_id' => 61,
                'trailer_id' => 26,
                'created_at' => '2021-04-29 15:22:51',
                'updated_at' => '2021-07-06 12:24:26',
            ),
            18 => 
            array (
                'id' => 25,
                'name' => 'harry potter và hòn đá phù thủy',
            'eng_name' => 'harry potter and the sorcerer\'s stone poster( 2001)',
                'description' => '<p>Harry Potter và Hòn Đá Phù Thủy là bộ phim đầu tiên trong series phim “Harry Potter” được xây dựng dựa trên tiểu thuyết của nhà văn J.K.Rowling. Nhân vật chính của phim, Harry Potter - một cậu bé 11 tuổi sau khi mồ côi cha mẹ đã bị gửi đến nhà dì dượng của mình, gia đình Dursley. Tuy nhiên, cậu bé bị ngược đãi và không hề biết về thân phận thực sự của mình. Vào sinh nhật thứ 11 của Harry, một người lai khổng lồ là Rubeus Hagrid đã đến tìm cậu bé để đưa cậu về trường Pháp Thuật Hogwarts. Lúc này, Harry mới biết được mình là phù thủy và một phần câu chuyện về cha mẹ mình, những người đã bị Voldemort giết hại. Cùng với trí thông minh và lòng dũng cảm, cậu bé đã cùng những người bạn của mình khám phá những điều bí mật nguy hiểm về thế giới của phép thuật...</p>',
                'language' => 'Anh',
                'studio' => 'Warner Bros',
                'releasedate' => '2001-11-04',
                'runtime' => 152,
                'avgrating' => 0.0,
                'view' => 1,
                'category_id' => 1,
                'country_id' => 2,
                'profileimage_id' => 70,
                'coverimage_id' => 71,
                'trailer_id' => 27,
                'created_at' => '2021-05-01 13:38:40',
                'updated_at' => '2021-05-07 12:46:39',
            ),
            19 => 
            array (
                'id' => 26,
                'name' => 'harry potter và phòng chứa bí mật',
            'eng_name' => 'harry potter and the chamber of secrets( 2020)',
                'description' => '<p>Harry trở lại năm thứ hai tại Hogwarts, nhưng phát hiện ra rằng những điều tồi tệ đang xảy ra bởi vì một trang web có tên là Phòng chứa bí mật đã được người thừa kế của Slytherin mở ra và sẽ khiến những đứa trẻ của Muggles, những kẻ không trong sạch, xuất hiện một cách bí ẩn bởi một con vật quái dị.</p>',
                'language' => 'Mỹ',
                'studio' => 'Warner Bros',
                'releasedate' => '2002-11-15',
                'runtime' => 161,
                'avgrating' => 0.0,
                'view' => 1,
                'category_id' => 1,
                'country_id' => 2,
                'profileimage_id' => 72,
                'coverimage_id' => 73,
                'trailer_id' => 28,
                'created_at' => '2021-05-01 13:47:12',
                'updated_at' => '2021-05-07 12:48:23',
            ),
            20 => 
            array (
                'id' => 27,
                'name' => 'harry potter và tên tù nhân ngục azkaban',
            'eng_name' => 'harry potter and the prisoner of azkaban( 2004)',
                'description' => '<p>Harry đang mong chờ đến cuối mùa hè để bắt đầu một khóa học mới tại Hogwarts, và rời khỏi ngôi nhà của người dì và người chú đáng khinh của mình, Dursley, càng sớm càng tốt. Điều Harry không biết là anh sẽ phải rời khỏi Privet Drive sớm và bất ngờ sau khi biến dì Marge của mình thành một quả bóng bay khổng lồ. Một chiếc xe buýt đêm, và tất nhiên là mê hoặc, sẽ đưa anh ta đến quán rượu Leaky Cauldron, nơi không ai khác ngoài Cornelius Fudge, Bộ trưởng Bộ Pháp thuật, đang chờ anh ta.</p>',
                'language' => 'Mỹ',
                'studio' => 'Warner Bros',
                'releasedate' => '2004-04-06',
                'runtime' => 141,
                'avgrating' => 0.0,
                'view' => 2,
                'category_id' => 1,
                'country_id' => 2,
                'profileimage_id' => 74,
                'coverimage_id' => 75,
                'trailer_id' => 29,
                'created_at' => '2021-05-01 13:53:29',
                'updated_at' => '2021-05-07 12:51:26',
            ),
            21 => 
            array (
                'id' => 28,
                'name' => 'harry potter và chiếc cốc lửa',
            'eng_name' => 'harry potter and the goblet of fire( 2005)',
                'description' => '<p>Khi giải Quidditch Thế giới bị cắt ngang bởi những kẻ ủng hộ Chúa tể Voldemort và sự trở lại của Dấu hiệu hắc ám khủng khiếp, Harry ý thức được rõ ràng rằng, Chúa tể Voldemort đang ngày càng mạnh hơn. Và để trở lại thế giới phép thuật, Chúa tể hắc ám cần phải đánh bại kẻ duy nhất sống sót từ lời nguyền chết chóc của hắn - Harry Potter. Vì lẽ đó, khi Harry bị buộc phải bước vào giải đấu Tam Pháp thuật uy tín nhưng nguy hiểm, cậu nhận ra rằng trên cả chiến thắng, cậu phải giữ được mạng sống của mình.</p>',
                'language' => 'Mỹ',
                'studio' => 'Warner Bros',
                'releasedate' => '2005-11-06',
                'runtime' => 157,
                'avgrating' => 0.0,
                'view' => 1,
                'category_id' => 1,
                'country_id' => 2,
                'profileimage_id' => 76,
                'coverimage_id' => 77,
                'trailer_id' => 30,
                'created_at' => '2021-05-01 14:00:54',
                'updated_at' => '2021-05-07 13:11:21',
            ),
            22 => 
            array (
                'id' => 29,
                'name' => 'harry potter và hội phượng hoàng',
            'eng_name' => 'harry potter and the order of the phoenix( 2007)',
                'description' => '<p>Harry tức giận vì bị bỏ rơi ở nhà Dursley trong dịp hè, cậu ngờ rằng Chúa tể hắc ám Voldemort đang tập hợp lực lượng, và vì cậu có nguy cơ bị tấn công, những người Harry luôn coi là bạn đang cố che giấu tung tích cậu. Cuối cùng, sau khi được giải cứu, Harry khám phá ra rằng giáo sư Dumbledore đang tập hợp lại Hội Phượng Hoàng – một đoàn quân bí mật đã được thành lập từ những năm trước nhằm chống lại Chúa tể Voldemort. Tuy nhiên, Bộ Pháp thuật không ủng hộ Hội Phượng Hoàng, những lời bịa đặt nhanh chóng được đăng tải trên Nhật báo Tiên tri – một tờ báo của giới phù thủy, Harry lo ngại rằng rất có khả năng cậu sẽ phải gánh vác trách nhiệm chống lại cái ác một mình.</p>',
                'language' => 'Mỹ',
                'studio' => 'Warner Bros',
                'releasedate' => '2007-11-07',
                'runtime' => 138,
                'avgrating' => 0.0,
                'view' => 5,
                'category_id' => 1,
                'country_id' => 2,
                'profileimage_id' => 78,
                'coverimage_id' => 79,
                'trailer_id' => 31,
                'created_at' => '2021-05-01 14:05:38',
                'updated_at' => '2021-11-04 16:07:00',
            ),
            23 => 
            array (
                'id' => 30,
                'name' => 'harry potter và hoàng tử lai',
            'eng_name' => 'harry potter and the half-blood prince( 2009)',
                'description' => '<p>Đây là năm thứ 6 của Harry Potter tại trường Hogwarts. Trong lúc những thế lực hắc ám của Voldemort gieo rắc nỗi kinh hoàng và sợ hãi ở khắp nơi, mọi chuyện càng lúc càng trở nên rõ ràng hơn đối với Harry, cậu sẽ sớm phải đối diện với định mệnh của mình. Draco Malfoy, kẻ thù không đội trời chung của Harry, có nhiều hành động khả nghi, luôn lén lút đi khắp trường. Vì thế, Harry cho rằng Draco là nội gián của Voldermort và quyết tâm tìm hiểu chính xác chuyện gì đang xảy ra...</p>',
                'language' => 'Mỹ',
                'studio' => 'Warner Bros',
                'releasedate' => '2009-08-07',
                'runtime' => 153,
                'avgrating' => 4.5,
                'view' => 5,
                'category_id' => 1,
                'country_id' => 2,
                'profileimage_id' => 80,
                'coverimage_id' => 81,
                'trailer_id' => 32,
                'created_at' => '2021-05-01 14:10:46',
                'updated_at' => '2021-05-07 12:51:32',
            ),
            24 => 
            array (
                'id' => 31,
                'name' => 'harry potter và bảo bối tử thần: phần 1',
            'eng_name' => 'harry potter and the deathly hallows – part 1( 2010)',
                'description' => '<p>Chúa tể Voldemort cùng đám tay chân của hắn đang âm mưu tấn công Harry Potter khi cậu rời khỏi ngôi nhà của gia đình Dursley lần cuối cùng. Ngay trước khi phép bảo vệ cho Harry tại gia đình Dursley hết hiệu lực vào thời điểm Harry bước qua tuổi 17, người của Hội Phượng hoàng đến để hộ tống cậu tới một nơi ở mới an toàn. Mặc dù đã dùng sáu người nguỵ trang thành Harry, Harry thật vẫn bị Voldemort cùng các Tử thần Thực tử phát hiện ra trên đường đi và bị tấn công...</p>',
                'language' => 'Mỹ',
                'studio' => 'Warner Bros',
                'releasedate' => '2010-11-19',
                'runtime' => 146,
                'avgrating' => 0.0,
                'view' => 9,
                'category_id' => 1,
                'country_id' => 2,
                'profileimage_id' => 82,
                'coverimage_id' => 83,
                'trailer_id' => 33,
                'created_at' => '2021-05-01 14:15:09',
                'updated_at' => '2021-05-08 14:21:12',
            ),
            25 => 
            array (
                'id' => 32,
                'name' => 'harry potter và bảo bối tử thần: phần 2',
            'eng_name' => 'harry potter and the deathly hallows – part 2( 2011)',
                'description' => '<p>Kết thúc phần 1 là khi nhóm bạn Harry Potter, Ron và Hermione quay trở lại trường Hogwarts để tìm và tiêu diệt Trường Sinh Linh Giá cuối cùng của Voldemort. Nhưng Voldemort đã phát hiện ra nhiệm vụ của họ, và trận chiến pháp thuật lớn nhất trong lịch sử đã diễn ra ở đây, nơi mà biết bao người ngã xuống, nơi mà tất cả các pháp sư dũng cảm sẵn sàng đánh đổi cuộc sống của mình để tiêu diệt tận cùng thế lực hắc ám. Giáo sư Dumbledore mặc dù đã mất từ tập 6, nhưng ở phần cuối ông vẫn đóng vai trò quan trọng trong việc dẫn đường chỉ lối cho Harry chiến đấu với phù thủy hắc ám mạnh nhất mọi thời đại...</p>',
                'language' => 'Mỹ',
                'studio' => 'Warner Bros',
                'releasedate' => '2011-07-15',
                'runtime' => 130,
                'avgrating' => 0.0,
                'view' => 5,
                'category_id' => 1,
                'country_id' => 2,
                'profileimage_id' => 84,
                'coverimage_id' => 85,
                'trailer_id' => 34,
                'created_at' => '2021-05-01 14:21:25',
                'updated_at' => '2021-05-19 11:17:53',
            ),
            26 => 
            array (
                'id' => 34,
            'name' => 'cậu bé mất tích( phần 2)',
            'eng_name' => 'stranger things (season 2) (2017)',
                'description' => '<p>Lấy bối cảnh những năm 1980 tại thị trấn Hawkins yên bình, cậu bé Will đột nhiên mất tích một cách bí ẩn. Mẹ cậu - Joyce ngày đêm tìm kiếm con trai mình trong tuyệt vọng. Bức màn dần được vén lên khi cô phát hiện ra rằng sự biến mất của Will rất có thể dính dáng đến chính phủ và những thế lực siêu nhiên. Cùng lúc đó, một cô bé sở hữu những khả năng kỳ dị đột nhiên xuất hiện...</p>',
                'language' => 'Mỹ',
                'studio' => 'netflix',
                'releasedate' => '2017-10-27',
                'runtime' => 50,
                'avgrating' => 0.0,
                'view' => 11,
                'category_id' => 2,
                'country_id' => 2,
                'profileimage_id' => 100,
                'coverimage_id' => 101,
                'trailer_id' => 37,
                'created_at' => '2021-05-07 14:35:02',
                'updated_at' => '2021-05-07 15:29:44',
            ),
            27 => 
            array (
                'id' => 35,
                'name' => 'liên minh công lý phiên bản của Zack Snyder',
                'eng_name' => 'Zack Snyder\'s justice league',
                'description' => '<p>Justice League hay còn được biết đến với cái tên Liên Minh Công Lý, là tập hợp những siêu anh hùng mang trong mình sức mạnh phi thường để giải cứu thế giới khỏi những thế lực đen tối trong vũ trụ DC. Lần này, nhân loại phải đối mặt với tên ác quỷ vô cùng tàn độc – Steppenwolf. Hắn là một trong những tay sai đắc lực của Darksied – một ác nhân và cũng chính là kẻ thù lớn nhất của Liên Minh Công Lý. Steppenwolf đã phô trương năng lực siêu phàm của mình, gieo rắc nỗi sợ hãi và bóng tối tới xứ Themyscira – quê hương của Wonder Woman và loài người.</p>',
                'language' => 'Mỹ',
                'studio' => 'Warner Bros',
                'releasedate' => '2021-03-18',
                'runtime' => 242,
                'avgrating' => 0.0,
                'view' => 6,
                'category_id' => 1,
                'country_id' => 2,
                'profileimage_id' => 135,
                'coverimage_id' => 136,
                'trailer_id' => 38,
                'created_at' => '2021-05-10 12:18:02',
                'updated_at' => '2021-08-13 02:12:47',
            ),
            28 => 
            array (
                'id' => 36,
                'name' => 'Percy Jackson & kẻ cắp tia chớp',
                'eng_name' => 'Percy Jackson & the Olympians: The Lightning Thief',
                'description' => '<p>Percy Jackson luôn gặp phải những rắc rối ở trường trung học nhưng hóa ra đó chỉ là những chuyện đơn giản của tuổi dậy thì. Còn thử thách mà cậu sẽ gặp phải chính là việc Percy khám phá ra rằng cha đẻ mình là Poseidon, vị thần biển cả, và điều đó có nghĩa rằng Percy là một á thần. Cùng lúc đó, thần Dớt, vua của các vị thần, đã buộc tội Percy ăn cắp vũ khí tối thượng của ông - tia sét quyền năng. Và bây giờ, tính mạng của Percy rơi vào vòng xoáy nguy hiểm, và cậu phải chuẩn bị cho một cuộc phiêu lưu lớn, với những giông bão hiểm nguy đang chờ dịp trút xuống thế giới…</p>',
                'language' => 'Anh',
                'studio' => '20th Century Fox',
                'releasedate' => '2010-02-02',
                'runtime' => 118,
                'avgrating' => 0.0,
                'view' => 5,
                'category_id' => 1,
                'country_id' => 2,
                'profileimage_id' => 162,
                'coverimage_id' => 163,
                'trailer_id' => 39,
                'created_at' => '2021-06-02 13:12:04',
                'updated_at' => '2021-07-05 01:12:42',
            ),
            29 => 
            array (
                'id' => 37,
                'name' => 'Percy Jackson: Biển Quái Vật',
            'eng_name' => 'Percy Jackson: Sea of Monsters (2013)',
                'description' => '<p>Dựa trên cuốn sách thứ hai trong loạt Riordan, Sea of Monsters là một câu chuyện trong đó Percy phải giải cứu "Trại Á thần," nơi trú ẩn an toàn duy nhất của những trẻ em á thần, chúng sẽ được bảo vệ khỏi sự nguy hiểm cập kè của Kronos - một lực lượng tà ác do bị đầu độc của những vị thần chính là những đứa con trai của mình, Kronos đã sống dậy và quyết định trút mọi tức giận lên đỉnh Olympus. Để cứu đồng loại Percy và bạn anh ấy phải dấn thân vào "Biển quái vật" để tìm "Bộ lông cừu vàng" ở vùng " Tam giác quỷ " vì đây là thứ duy nhất có thể bảo vệ trại biên giới của họ.</p>',
                'language' => 'Mỹ',
                'studio' => '20th Century Fox',
                'releasedate' => '2013-08-07',
                'runtime' => 106,
                'avgrating' => 0.0,
                'view' => 2,
                'category_id' => 1,
                'country_id' => 2,
                'profileimage_id' => 168,
                'coverimage_id' => 169,
                'trailer_id' => 42,
                'created_at' => '2021-06-02 13:18:54',
                'updated_at' => '2021-11-04 16:08:14',
            ),
            30 => 
            array (
                'id' => 38,
                'name' => 'công phu gấu trúc',
            'eng_name' => 'kung fu panda (2008)',
                'description' => '<p>Po là một chú gấu trúc to béo, ham ăn và mê môn võ kungfu. Trong một ngày hội, lời tiên tri từ xưa đã giúp Po có thể thực hiện ước mơ của mình. Po được học với sư phụ Shifu và nhóm Ngũ Hùng. Nhưng vấn đề ở chỗ cậu chàng lại là kẻ lười biếng nhất thung lũng Thanh Bình. Và rồi mọi chuyện hoàn toàn thay đổi khi con báo tuyết gian ác Tai Lung trốn thoát khỏi tù. Hắn ráo riết lên kế hoạch tấn công thung lũng. Và người anh hùng được chọn để chiến đấu chống lại Tai Lung, không ai khác chính là Po béo. Một đội ngũ hùng hậu những bậc thầy kungfu được huy động để hướng dẫn Po những miếng võ cơ bản nhất…</p>',
                'language' => 'Anh',
                'studio' => 'DreamWorks Animation',
                'releasedate' => '2008-05-06',
                'runtime' => 90,
                'avgrating' => 0.0,
                'view' => 3,
                'category_id' => 1,
                'country_id' => 2,
                'profileimage_id' => 170,
                'coverimage_id' => 171,
                'trailer_id' => 43,
                'created_at' => '2021-06-02 13:38:31',
                'updated_at' => '2021-06-02 13:43:06',
            ),
            31 => 
            array (
                'id' => 39,
                'name' => 'Công Phu Gấu Trúc 2',
            'eng_name' => 'kung fu panda 2 (2011)',
                'description' => '<p>Cuộc sống của Po hiện tại đẹp như một giấc mơ: trở thành Thần Long Đại Hiệp, bảo vệ Thung Lũng Yên Bình cùng với những người bạn và các sư huynh và sư tỷ kung fu đồng môn là Ngũ Đại Hào Kiệt. Thế nhưng, cuộc sống mới của Po bỗng dưng bị đe dọa với sự xuất hiện của một thế lực đen tối khủng khiếp. Hắn sử dụng một vũ khí bí mật và không có gì ngăn chặn nổi, nhằm xâm chiếm Trung Hoa và hủy diệt hoàn toàn môn võ kung fu. Po và The Furious Five phải có một cuộc hành trình băng qua lục địa Trung Hoa nhằm tiêu diệt thế lực xấu xa đó. Nhưng làm thế nào Po có thể chặn đứng một thứ vũ khí mà nó có thể chặn đứng tuyệt đỉnh kung fu?</p>',
                'language' => 'Mỹ',
                'studio' => 'DreamWorks Animation',
                'releasedate' => '2011-05-25',
                'runtime' => 91,
                'avgrating' => 0.0,
                'view' => 1,
                'category_id' => 1,
                'country_id' => 2,
                'profileimage_id' => 172,
                'coverimage_id' => 173,
                'trailer_id' => 44,
                'created_at' => '2021-06-02 13:42:48',
                'updated_at' => '2021-06-02 13:43:13',
            ),
            32 => 
            array (
                'id' => 40,
                'name' => 'Kẻ Đánh Cắp Giấc Mơ',
            'eng_name' => 'Inception (2010)',
                'description' => '<p>Dom Cobb không phải là một đạo chích tầm thường, anh ta là bực thầy về đánh cắp, có thể xâm nhập vào cõi vô thức của bất kỳ người nào để đánh cắp những bí mật thầm kín nhất của người đó. Muốn thực hiện chuyện này, anh ta bước vào những giấc mơ của người đó. “Chúng ta tạo ra thế giới của giấc mơ. Chúng ta đưa đối tượng vào thế giới giấc mơ đó và đối tượng sẽ phun ra hết những bí mật, rồi chúng ta sẽ đánh cắp các bí mật đó.” Nhưng đã đến lúc Cobb mệt mỏi với những tội phạm thực hiện theo yêu cầu của các tổng công ty. Anh muốn quay lại cuộc sống bình thường như mọi người. Muốn vậy, anh phải làm một công tác cuối cùng cho Saito, một đại gia nắm tẩy của Cobb trước nhà chức trách Mỹ. Nhưng thay vì đánh cắp thông tin, Saito muốn cấy một ý tưởng vào óc của tổng công ty đối thủ cạnh tranh. Khi đã mang ý tưởng ấy rồi, đối thủ này chỉ có một con đường là sập tiệm.</p>',
                'language' => 'Mỹ',
                'studio' => 'Legendary Entertainment',
                'releasedate' => '2010-06-08',
                'runtime' => 148,
                'avgrating' => 0.0,
                'view' => 3,
                'category_id' => 1,
                'country_id' => 2,
                'profileimage_id' => 174,
                'coverimage_id' => 175,
                'trailer_id' => 45,
                'created_at' => '2021-06-02 13:50:08',
                'updated_at' => '2021-08-13 02:07:50',
            ),
            33 => 
            array (
                'id' => 41,
            'name' => 'học viện umbrella( phần 2)',
                'eng_name' => 'the umbrella academy season 2',
                'description' => '<p>Đoàn tụ vì cái chết của cha, những anh chị em xa cách sở hữu năng lực siêu phàm bàng hoàng phát hiện ra bí mật gia đình -- và một nguy cơ đang dần hiện hữu với nhân loại.</p>',
                'language' => 'Mỹ',
                'studio' => 'netflix',
                'releasedate' => '2020-07-31',
                'runtime' => 50,
                'avgrating' => 0.0,
                'view' => 8,
                'category_id' => 2,
                'country_id' => 2,
                'profileimage_id' => 176,
                'coverimage_id' => 177,
                'trailer_id' => 46,
                'created_at' => '2021-06-02 13:56:29',
                'updated_at' => '2022-04-07 14:15:37',
            ),
            34 => 
            array (
                'id' => 43,
                'name' => 'Vương Triều Xác Sống',
                'eng_name' => 'Kingdom season 1',
            'description' => '<p>Vương Triều Xác Sống (Kingdom) 2019 là phim hàn quốc lấy bối cảnh thời Joseon, Thái tử Lee Chang (Joo Ji Hoon) có nhiệm vụ điều tra một dịch bệnh bí ẩn đang hoành hành trên khắp đất nước. Mọi chuyện bắt đầu lệch khỏi quỹ đạo khi Lee Chang phát hiện loại bệnh này liên quan đến xác sống. Chưa kể, các thế lực trong triều đình đối với thứ "dịch bệnh" này có nhiều phương thức xử lý khác nhau với mục tiêu lớn nhất là bảo vệ quyền lợi cá nhân, gây nên cục diện rối loạn thảm khốc.</p>',
                'language' => 'Hàn Quốc',
                'studio' => 'netflix',
                'releasedate' => '2019-01-25',
                'runtime' => 60,
                'avgrating' => 0.0,
                'view' => 6,
                'category_id' => 2,
                'country_id' => 4,
                'profileimage_id' => 192,
                'coverimage_id' => 193,
                'trailer_id' => 49,
                'created_at' => '2021-06-02 14:31:21',
                'updated_at' => '2021-06-02 14:54:07',
            ),
            35 => 
            array (
                'id' => 44,
            'name' => 'Vương Triều Xác Sống (Phần 2)',
                'eng_name' => 'Kingdom season 2',
            'description' => '<p>Vương Triều Xác Sống (Phần 2) (Kingdom) Trong khi những tin đồn kỳ lạ về vị vua lâm bệnh khiến cả vương quốc xôn xao, thái tử trở thành hy vọng duy nhất của dân chúng trước một bệnh dịch bí ẩn đang lan rộng.</p>',
                'language' => 'Hàn Quốc',
                'studio' => 'netflix',
                'releasedate' => '2020-03-13',
                'runtime' => 60,
                'avgrating' => 0.0,
                'view' => 6,
                'category_id' => 2,
                'country_id' => 2,
                'profileimage_id' => 194,
                'coverimage_id' => 195,
                'trailer_id' => 50,
                'created_at' => '2021-06-02 14:34:28',
                'updated_at' => '2021-06-02 15:07:00',
            ),
            36 => 
            array (
                'id' => 45,
                'name' => 'Captain America: Kẻ báo thù đầu tiên',
            'eng_name' => 'Captain America: The First Avenger (2011)',
            'description' => '<p>lấy bổi cách từ đầu năm 1942, khi Mỹ đang tham gia Thế chiến thứ II và cần tới những chiến binh can trường. Chàng trai Steve Rogers (Chris Evans) là một người như vậy, nhưng thể hình quá thấp bé khiến anh không thể đạt được ước mơ tòng quân. Cơ may đến với Rogers khi anh được chọn tham gia một thí nghiệm của chính phủ, giúp biến người thường trở thành siêu chiến binh.</p><p>Mọi việc diễn ra suôn sẻ, biến Rogers thành một người cao to vạm vỡ, đầu óc tiếp thu mọi kỹ năng chiến đấu nhanh và vẫn giữ được trái tim nhân hậu.Anh trở thành Captain America, biểu tượng của nước Mỹ kể từ đó. Đối thủ của anh là phe Phát-xít, với quái nhân Red Skull, kẻ không chỉ quyền năng mà còn rất tàn ác.</p>',
                'language' => 'Mỹ',
                'studio' => 'marvel',
                'releasedate' => '2011-07-22',
                'runtime' => 124,
                'avgrating' => 0.0,
                'view' => 6,
                'category_id' => 1,
                'country_id' => 2,
                'profileimage_id' => 209,
                'coverimage_id' => 210,
                'trailer_id' => 51,
                'created_at' => '2021-06-02 15:18:45',
                'updated_at' => '2022-04-07 12:58:43',
            ),
            37 => 
            array (
                'id' => 46,
                'name' => 'Captain America 2: Chiến Binh Mùa Đông',
            'eng_name' => 'Captain America 2: The Winter Soldier (2014)',
            'description' => '<p>Nội dung phim Captain America: Chiến Binh Mùa Đông là câu chuyện tiếp nối bộ phim The Avengers, khi Steve Rogers phải tìm cách hòa nhập vào thế giới hiện đại và kết hợp với Natasha Romanoff/Black Widow để chiến đấu chống lại một kẻ thù nguy hiểm ở Washington, D.C. Sau cuộc chiến cùng đội The Avengers tại New York, Captain America (hay còn gọi là Steve Rogers) có một cuộc sống khá thầm lặng tại Washington và anh phải vật lộn để thích nghi với cuộc sống ở thế giới hiện đại. Tuy nhiên, khi một người bạn trong SHIELD bị rơi vào vòng nguy hiểm, anh đã bị kéo vào một âm mưu đen tối có thể phá hủy cả nhân loại. Trong phim này, cùng với Black Widow, anh phải ngăn cản âm mưu này đồng thời chiến đấu chống lại nhừng sát thủ chuyên nghiệp được cử tới để thủ tiêu mình. Cặp đôi Captain, Black Widow còn tranh thủ sự giúp đỡ từ người bạn mới, Falcon. Tuy nhiên, một kẻ thù vô cùng nguy hiểm và bí ẩn lúc này lại xuất hiện.</p>',
                'language' => 'Mỹ',
                'studio' => 'marvel',
                'releasedate' => '2014-04-04',
                'runtime' => 136,
                'avgrating' => 0.0,
                'view' => 0,
                'category_id' => 1,
                'country_id' => 2,
                'profileimage_id' => 211,
                'coverimage_id' => 212,
                'trailer_id' => 52,
                'created_at' => '2021-06-02 15:23:32',
                'updated_at' => '2021-06-02 15:23:32',
            ),
            38 => 
            array (
                'id' => 47,
                'name' => 'Captain America 3: Nội Chiến Siêu Anh Hùng',
            'eng_name' => 'Captain America 3: Civil War (2016)',
            'description' => '<p>Captain America: Civil War (Nội Chiến Siêu Anh Hùng) xoay quanh việc Steve Rogers (Captain America) dẫn đầu một nhóm siêu anh hùng với các thành viên của Avengers với mục tiêu tiếp tục nỗ lực để bảo vệ nhân loại. Nhưng sau nhiều vụ việc xảy ra do biệt đội Avengers làm thiệt hại tài sản, chính phủ đã thiết lập cơ quan quản lý và giám sát nhóm. Điều này gây ra sự chia rẽ trong nội bộ nhóm Avengers, tạo nên hai phe đối đầu nhau. Một bên được lãnh đạo bởi Steve Rogers (Captain America) với mong muốn duy trì nhóm để thực hiện mục tiêu bảo vệ nhân loại mà không có sự can thiệp của chính phủ. Phe còn lại là của Tony Stark (Iron Man) luôn hỗ trợ giám sát và có trách nhiệm giải trình mọi việc làm với chính phủ.</p>',
                'language' => 'Mỹ',
                'studio' => 'marvel',
                'releasedate' => '2016-06-05',
                'runtime' => 147,
                'avgrating' => 0.0,
                'view' => 3,
                'category_id' => 1,
                'country_id' => 2,
                'profileimage_id' => 213,
                'coverimage_id' => 214,
                'trailer_id' => 53,
                'created_at' => '2021-06-02 15:26:33',
                'updated_at' => '2022-04-07 13:18:22',
            ),
        ));
        
        
    }
}